
/* eslint-disable import/prefer-default-export */

// User MUTATIONS
export const MARKERS_OBJECT = 'MARKERS_OBJECT';
export const ADD_MARKET_OBJECT = 'ADD_MARKET_OBJECT';
export const ADD_MARKER_POSITION = 'ADD_MARKER_POSITION';

// Movimento MUTATIONS
export const MOVIMENTO_MARKERS_OBJECT = 'MOVIMENTO_MARKERS_OBJECT';
export const MOVIMENTO_ADD_MARKER_OBJECT = 'MOVIMENTO_ADD_MARKER_OBJECT';
export const MOVIMENTO_ADD_MARKER_POSITION = 'MOVIMENTO_ADD_MARKER_POSITION'; 
